name: maze_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  freezed: ^2.5.2
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  logger: ^2.3.0
  flutter_bloc: ^8.1.5
  flutter_otp_text_field: ^1.1.3+2
  #otp_timer_button: ^1.1.1
  timer_button_fork: ^4.0.1
  shared_preferences: ^2.2.3
  encrypt: ^5.0.3
  string_validator: ^1.1.0
  jwt_decoder: ^2.0.1
  fluttertoast: ^8.2.6

  cupertino_icons: ^1.0.6
  calendar_date_picker2: ^1.1.4
  image_picker: ^1.1.2
  percent_indicator: ^4.2.3
  flutter_native_splash: ^2.4.0
  introduction_screen: ^3.1.14
  flutter_screenutil: ^5.9.3
  file_picker: ^8.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.10
  json_serializable: ^6.8.0


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

 
  assets:
     - assets/images/
     - assets/icons/
     - assets/images/intro/
     
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist-ThinItalic.ttf

